pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = 'jilujose2004'
        IMAGE_NAME = 'simple-task-manager'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        EC2_USER = 'ubuntu'
        EC2_HOST = 'ec2-3-95-66-80.compute-1.amazonaws.com'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} -t ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest ./task-manager"
            }
        }

        stage('Health Validation') {
            steps {
                sh "docker run -d -p 9090:80 --name test-container ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
                sleep time: 5, unit: 'SECONDS'
                sh 'curl -f http://localhost:9090 || exit 1'
                sh 'docker stop test-container'
                sh 'docker rm test-container'
            }
        }

        stage('Push to Registry') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', passwordVariable: 'DOCKER_PASS', usernameVariable: 'DOCKER_USER')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh "docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
                    sh "docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest"
                }
            }
        }

        stage('Deploy to AWS EC2') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} 'docker pull ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest && (docker stop task-manager-container || true) && (docker rm task-manager-container || true) && docker run -d -p 80:80 --name task-manager-container ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest'
                    """
                }
            }
        }
    }
}
